ifeq ($(PROJECT),diabloxplus_kk)
EXTRA_CFLAGS += -DDIABLOXPLUS_KK_IPHONE
endif
obj-$(CONFIG_MTK_ACCDET) := accdet.o

ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/power\
             -I$(MTK_PATH_SOURCE)/drivers/power\
