#ifndef RCV_CUST_KEYS_H
#define RCV_CUST_KEYS_H

#include <linux/input.h>
//JRD PR672615 start
#define RECOVERY_KEY_DOWN     KEY_VOLUMEDOWN
#define RECOVERY_KEY_UP       KEY_VOLUMEUP
#define RECOVERY_KEY_ENTER    KEY_POWER
#define RECOVERY_KEY_MENU     KEY_HOMEPAGE
//JRD PR672615 end

#endif /* RCV_CUST_KEYS_H */
